### ISSUE TITLE
Latest Commit Broken on Arch Linux/Non-Flatpak

### ISSUE THREAD

**Issue by witchymary** [Faugus/faugus-launcher#25]
Commit https://github.com/Faugus/faugus-launcher/commit/015c83f2520fffdda55cdd1502d8508e898ff52e broke the launcher for me on Arch Linux. Here's the crash log:

```
Traceback (most recent call last):
  File "/usr/bin/faugus-launcher", line 3592, in <module>
    main()
  File "/usr/bin/faugus-launcher", line 3563, in main
    if is_already_running():
       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/faugus-launcher", line 51, in is_already_running
    with open(lock_file_path, 'w') as lock_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/witchymary/.local/share/faugus-launcher/faugus_launcher.lock'
```

**Comment by Faugus** [comment]
Thanks for reporting.
It should work now.

**Comment by witchymary** [comment]
Thank you. It's working fine now.
